# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkEYlJ4DB31FMjk9lZmbbRQ0moeOg4n-
"""

import yfinance as yf

class Crypto_News:
  
  """
  Description: This function allows you to fetch news related to crypto currency.
  You can fetch the entire bag of crypto news and can also fetch news specific to
  a coin.
  Parameters: Symbol of Crypto Currency
  Returns: News related to the parameter passed

  """

  def crypto_news(self,crypto_name):
    return yf.Ticker(crypto_name).news

crypto=Crypto_News()
crypto.crypto_news("BTC")